[[servers]]
  port = 3035
  hostName = "localhost"
  documentRoot = htdocs

  [servers.errorPages]
    not_found = ./htdocs/error_pages/404.html
    forbidden = ./htdocs/error_pages/403.html
    server_error = "./htdocs/error_pages/500.html"

  [[servers.locations]]
    path = "/"
    root = "htdocs"
    index = "index.html"

  [[servers.locations]]
    path = "/images"
    root = "/path/to/server1/images"

[[servers]]
  port = 9090
  hostName = "second server"
  documentRoot = htdocs

  [servers.errorPages]
    not_found = ./htdocs/error_pages/404.html
    forbidden = ./htdocs/error_pages/403.html
    server_error = "./htdocs/error_pages/500.html"

  [[servers.locations]]
    path = "/"
    root = "htdocs"
    index = "index.html"

  [[servers.locations]]
    path = "/images"
    root = "/path/to/server1/images"

