[[servers]]
  port = 8080
  hostName = localhost
  documentRoot = htdocs

  [servers.errorPages]
    not_found = htdocs/errorPages/404.html
    server_error = htdocs/errorPages/500.html

  [[servers.locations]]
    path = /
    root = htdocs
    index = index.html

  [[servers.locations]]
    path = /images
    root = htdocs/images
